<a href="https://colab.research.google.com/github/katyayani-jha/ML-LAB-CS12/blob/main/ML_Lab_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Katyayani Jha | 3P12 | 102216040

1 Questions on Basic NumPy Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array_method1 = array1.flatten()
flattened_array_method2 = array1.ravel()
print("Flattened array (method 1):", flattened_array_method1)
print("Flattened array (method 2):", flattened_array_method2)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
arrays_equal = np.array_equal(arr1, arr2)
print("Are arr1 and arr2 equal?", arrays_equal)

Reversed array: [5 4 6 3 2 1]
Flattened array (method 1): [1 2 3 2 4 5 1 2 3]
Flattened array (method 2): [1 2 3 2 4 5 1 2 3]
Are arr1 and arr2 equal? True


In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
x_unique, x_counts = np.unique(x, return_counts=True)
x_most_frequent_value = x_unique[np.argmax(x_counts)]
x_indices = np.where(x == x_most_frequent_value)[0]

print("Array x:")
print("Most frequent value:", x_most_frequent_value)
print("Indices:", x_indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
y_unique, y_counts = np.unique(y, return_counts=True)
y_most_frequent_value = y_unique[np.argmax(y_counts)]
y_indices = np.where(y == y_most_frequent_value)[0]

print("\nArray y:")
print("Most frequent value:", y_most_frequent_value)
print("Indices:", y_indices)

Array x:
Most frequent value: 1
Indices: [0 5 7 8 9]

Array y:
Most frequent value: 1
Indices: [0 1 2]


In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = gfg.sum()

# Row-wise
sum_row_wise = gfg.sum(axis=1)

# Column-wise
sum_column_wise = gfg.sum(axis=0)

print("Sum of all elements:", sum_all_elements)
print("Sum of all elements row-wise:", sum_row_wise)
print("Sum of all elements column-wise:", sum_column_wise)

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# Sum of diagonal elements
sum_diagonal = np.trace(n_array)

# Eigenvalues and eigenvectors of matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)

# Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)

# Determinant of matrix
determinant = np.linalg.det(n_array)

print("Sum of diagonal elements:", sum_diagonal)
print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)
print("Inverse of the matrix:\n", inverse_matrix)
print("Determinant of the matrix:", determinant)

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
import numpy as np

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.matmul(p1, q1)
covariance1 = np.cov(p1.flatten(), q1.flatten())

print("Case i:")
print("Product of p1 and q1:")
print(product1)
print("Covariance matrix between p1 and q1:")
print(covariance1)


p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.matmul(p2, q2)
covariance2 = np.cov(p2.flatten(), q2.flatten())

print("\nCase ii:")
print("Product of p2 and q2:")
print(product2)
print("Covariance matrix between p2 and q2:")
print(covariance2)

Case i:
Product of p1 and q1:
[[16 19]
 [26 31]]
Covariance matrix between p1 and q1:
[[0.66666667 1.        ]
 [1.         1.66666667]]

Case ii:
Product of p2 and q2:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix between p2 and q2:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
import numpy as np
from scipy.spatial import distance

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.dot(x, y.T)

outer_products = []
for row_x in x:
    for row_y in y:
        outer_product = np.outer(row_x, row_y)
        outer_products.append(outer_product)

# Using broadcasting to compute the Cartesian product of two matrices
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print("Inner Product:")
print(inner_product)

print("\nOuter Products:")
for i, outer_product in enumerate(outer_products):
    print(f"Outer Product {i+1}:")
    print(outer_product)

print("\nCartesian Product:")
print(cartesian_product)

Inner Product:
[[17 52]
 [13 62]]

Outer Products:
Outer Product 1:
[[ 2 10  0]
 [ 3 15  0]
 [ 4 20  0]]
Outer Product 2:
[[10 20  6]
 [15 30  9]
 [20 40 12]]
Outer Product 3:
[[ 3 15  0]
 [ 2 10  0]
 [ 9 45  0]]
Outer Product 4:
[[15 30  9]
 [10 20  6]
 [45 90 27]]

Cartesian Product:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


2 Questions based on NumPy Mathematics & Statistics

In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

# Finding element-wise absolute value
absolute_values = np.abs(array)

# Finding the 25th, 50th, and 75th percentile of the flattened array, for each column, and for each row

flattened_array = array.flatten()

percentiles_flattened = {
    '25th': np.percentile(flattened_array, 25),
    '50th': np.percentile(flattened_array, 50),
    '75th': np.percentile(flattened_array, 75)
}

percentiles_columns = {
    '25th': np.percentile(array, 25, axis=0),
    '50th': np.percentile(array, 50, axis=0),
    '75th': np.percentile(array, 75, axis=0)
}

percentiles_rows = {
    '25th': np.percentile(array, 25, axis=1),
    '50th': np.percentile(array, 50, axis=1),
    '75th': np.percentile(array, 75, axis=1)
}

# Mean, Median, and Standard Deviation of the flattened array

mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_dev_flattened = np.std(flattened_array)

# Mean, Median, and Standard Deviation for each column

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

# Mean, Median, and Standard Deviation for each row

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("Element-wise Absolute Values:")
print(absolute_values)

print("\nPercentiles of Flattened Array:")
print(percentiles_flattened)

print("\nPercentiles for Each Column:")
print(percentiles_columns)

print("\nPercentiles for Each Row:")
print(percentiles_rows)

print("\nMean, Median, and Standard Deviation of Flattened Array:")
print(f"Mean: {mean_flattened}")
print(f"Median: {median_flattened}")
print(f"Standard Deviation: {std_dev_flattened}")

print("\nMean, Median, and Standard Deviation for Each Column:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Standard Deviation: {std_dev_columns}")

print("\nMean, Median, and Standard Deviation for Each Row:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Standard Deviation: {std_dev_rows}")

Element-wise Absolute Values:
[[1 2 3]
 [4 5 6]]

Percentiles of Flattened Array:
{'25th': -3.5, '50th': -0.5, '75th': 2.5}

Percentiles for Each Column:
{'25th': array([-2.75, -0.25, -3.75]), '50th': array([-1.5,  1.5, -1.5]), '75th': array([-0.25,  3.25,  0.75])}

Percentiles for Each Row:
{'25th': array([-0.5, -5. ]), '50th': array([ 1., -4.]), '75th': array([2. , 0.5])}

Mean, Median, and Standard Deviation of Flattened Array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, and Standard Deviation for Each Column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation for Each Row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [ ]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)

ceiling_values = np.ceil(a)

truncated_values = np.trunc(a)

rounded_values = np.round(a)

print("Original Array:")
print(a)

print("\nFloor Values:")
print(floor_values)

print("\nCeiling Values:")
print(ceiling_values)

print("\nTruncated Values:")
print(truncated_values)

print("\nRounded Values:")
print(rounded_values)

Original Array:
[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor Values:
[-2. -2. -1.  0.  1.  1.  3.]

Ceiling Values:
[-1. -1. -0.  1.  2.  2.  3.]

Truncated Values:
[-1. -1. -0.  0.  1.  1.  3.]

Rounded Values:
[-2. -2. -0.  0.  2.  2.  3.]


3 Questions based on Searching & Sorting

In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)

sorted_indices = np.argsort(array)

four_smallest = np.partition(array, 4)[:4]

five_largest = np.partition(array, -5)[-5:]

print("Original Array:")
print(array)

print("\nSorted Array:")
print(sorted_array)

print("\nIndices of Sorted Array:")
print(sorted_indices)

print("\n4 Smallest Elements:")
print(four_smallest)

print("\n5 Largest Elements:")
print(five_largest)

Original Array:
[ 10  52  62  16  16  54 453]

Sorted Array:
[ 10  16  16  52  54  62 453]

Indices of Sorted Array:
[0 3 4 1 5 2 6]

4 Smallest Elements:
[16 10 16 52]

5 Largest Elements:
[ 16  52  62  54 453]


In [ ]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[np.isclose(array, np.round(array))]

float_elements = array[~np.isclose(array, np.round(array))]

print("Original Array:")
print(array)

print("\nInteger Elements Only:")
print(integer_elements)

print("\nFloat Elements Only:")
print(float_elements)

Original Array:
[1.  1.2 2.2 2.  3.  2. ]

Integer Elements Only:
[1. 2. 3. 2.]

Float Elements Only:
[1.2 2.2]


4 File Path for Image

In [ ]:
from google.colab import files
uploaded = files.upload()

from PIL import Image
import numpy as np

def img_to_array(path, save_path):
    # Opening the image file
    with Image.open(path) as img:
        # Converting the image to an array
        img_array = np.array(img)

        # Saving the array to a text file
        np.savetxt(save_path, img_array.reshape(-1, img_array.shape[2]) if img_array.ndim == 3 else img_array, fmt='%d')

        print(f"Image array saved to {save_path}")

img_to_array('pic.png', 'saved_image_array.txt')

Saving pic.png to pic.png
Image array saved to saved_image_array.txt


Image array saved to saved_image_array.txt


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def load_and_display_image(file_path, shape):
    # Loading the array from the text file
    img_array = np.loadtxt(file_path, dtype=int).reshape(shape)

    # Displaying the image
    plt.imshow(img_array, cmap='gray' if len(shape) == 2 else None)
    plt.axis('off')  # Hide axes
    plt.show()

# For grayscale image
# load_and_display_image('saved_image_array.txt', (height, width))

# For RGB image
# load_and_display_image('saved_image_array.txt', (height, width, 3))

from google.colab import files
files.download('saved_image_array.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>